spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:/Users/jowontae/tmp/customer
    username: sa
    password:
  jpa:
    hibernate.ddl-auto: validate
  thsymeleaf.cache: false